### ISSUE TITLE
tpe, tpe_pred = build_tpe(n_in, n_out, W_pca.T)

### ISSUE THREAD

**Issue by noelcodes** [bruceyang2012/Face-identification-with-cnn-triplet-loss#4]
HI I'm stuck here. 
keras merge keep error me out. 

In [13]: tpe, tpe_pred = build_tpe(n_in, n_out, W_pca.T)
D:\xrvision\XRV_projects\Face-identification-with-cnn-triplet-loss\model.py:67: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(18, input_dim=18, weights=[array([[-..., activation="linear", use_bias=False)`
  base_model.add(Dense(n_out, input_dim=n_in, bias=False, weights=[W_pca], activation='linear'))
Traceback (most recent call last):

  File "<ipython-input-13-cfcacab54beb>", line 1, in <module>
    tpe, tpe_pred = build_tpe(n_in, n_out, W_pca.T)

  File "D:\xrvision\XRV_projects\Face-identification-with-cnn-triplet-loss\model.py", line 75, in build_tpe
    e = merge([a_emb, p_emb, n_emb], mode=triplet_merge, output_shape=triplet_merge_shape)

TypeError: 'module' object is not callable

**Comment by noelcodes** [comment]
downgrade to keras=2.0.4 seem to work.
But hit into next error at eer = test()

In [21]: eer, _, _, _ = calc_metrics(tsc, isc)
Traceback (most recent call last):

  File "<ipython-input-21-470647bcaeeb>", line 1, in <module>
    eer, _, _, _ = calc_metrics(tsc, isc)

  File "D:\xrvision\XRV_projects\Face-identification-with-cnn-triplet-loss\identification.py", line 12, in calc_metrics
    min_score = np.minimum(np.min(targets_scores), np.min(imposter_scores))

  File "C:\Users\Noel Tam\AppData\Local\conda\conda\envs\tripletloss\lib\site-packages\numpy\core\fromnumeric.py", line 2442, in amin
    initial=initial)

  File "C:\Users\Noel Tam\AppData\Local\conda\conda\envs\tripletloss\lib\site-packages\numpy\core\fromnumeric.py", line 83, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by noelcodes** [comment]
no matter what, "isc" always comes out empty, which triggers the error. It just seems the model is unable to separate the imposer and target well. I'm stuck here... If i hard code a random value into isc (just to move on), the prediction is meaningless, it doesn't recognize an imposer. So this part is kind of important.
